name: emit latest gitdash

on:
  push:
    branches: ["main"]
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron: "30 5,17 * * *" # triggers the workflow every day at 5:30 and 17:30 UTC:

# # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

jobs:
  emit-out-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Cache Python dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.12  # Set the desired Python version (optional)

      - name: Install dependencies
        run: pip install -r requirements.txt # Ensure there is requirements.txt with necessary dependencies

      - name: Run Python script to emit out.md
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --local user.email "lloydlobo4@gmail.com"
          git config --local user.name "lloydlobo"
          if ! git diff --exit-code; then
              git add out.md
              git commit -am "ci(workflows): emit latest out.md $(date)"
              git push origin main
          fi
