name: emit latest gitdash

on:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron: "30 5,17 * * *" # triggers the workflow every day at 5:30 and 17:30 UTC:
  push:
    branches: ["main"]
    # paths:
      # - "out.md"
  workflow_dispatch: # Allows you to run this manually for testing

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
#   pages: write
#   id-token: write

jobs:
  emit-out-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Good practice for rebasing/pushing

      # - name: Cache Python dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12  # Set the desired Python version (optional)
          cache: 'pip' # Built-in caching is simpler than actions/cache

      - name: Install dependencies
        run: pip install -r requirements.txt # Ensure there is requirements.txt with necessary dependencies

      - name: Run Python script to emit out.md
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python main.py

      - name: Join front-matter with out.md & tee to README.md
        env:
          FRONT_MATTER: |
            # gitdash
            
            Listing my personal public repositories for a high-level progression overview.
            
        run: |    
          echo "$FRONT_MATTER" > README.md
          cat out.md >> README.md

      # - name: 'Upload Artifact'
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: updated-out-md-artifact
      #     path: out.md
      #     retention-days: 5 # Min 1, Max 90, unless changed from repository settings

      - name: Commit and push changes
        # uses: actions/checkout@v4.1.1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          
          # Check if there are changes to avoid empty commit errors
          if [[ -n "$(git status --porcelain)" ]]; then
              git add out.md README.md
              git commit -m "ci(actions): update latest gitdash $(date +'%Y-%m-%d %H:%M')"
              git pull --rebase origin main
              git push origin main
          else
              echo "No changes detected, skipping commit."
          fi
        # run: |
        #   git config --local user.email "actions@github.com"
        #   git config --local user.name "Github Actions"
        #   if ! git diff --exit-code; then
        #       git pull --rebase origin main
        #       git add out.md README.md
        #       git commit -am "ci(actions): update latest gitdash $(date)"
        #       git push origin main
        #   fi
